### ISSUE TITLE
THEOREMS.md reference `kind` executable

### ISSUE THREAD

**Issue by dvberkel** [uwu-tech/Kind#257]
### Describe the bug
When installing the Kind toolchain the `kind-scm` command is installed. When I read [`THEOREMS.md`][theorems] the command is named `kind`.

### To Reproduce
1. Following [installation instructions](https://github.com/uwu-tech/Kind/blob/master/INSTALL.md) for Ubuntu
2. Read [`THEOREMS.md`][theorems]

### Expected behavior
I would expect that the command referenced in the the `THEOREMS.md` to be called `kind-scm`.

### Environment (please complete the following information):
 - OS: Ubuntu
 - Kind version: kind@1.0.86

### Additional context
It might be that the `kind` command is renamed due to conflicts with Kubernetes as mentioned in issue #242 

[theorems]: https://github.com/uwu-tech/Kind/blob/master/THEOREMS.md

**Comment by dvberkel** [comment]
I am more than willing to make the change in the documentation if it is indeed the case that it should read `kind-scm`.

**Comment by rigille** [comment]
I agree the documentation commands should work without changes. What's happening is that the language has two releases: a javascript release called `kind` and a newer scheme release called `kind-scm`. I think the solution is to rename the js release as `kind-js` and give the option to create `kind` as an alias in both installations. What do you think? Also, was the installation process smooth for you?

**Comment by dvberkel** [comment]
Ah, that makes sense. I did not install Kind from npm.

Your suggestion seems reasonable to me. It would also sit nice with issue #242.

The installation process went with a small hitch, but nothing that I could not solve myself. It might be off topic, but the hitch was that I installed the latest debian binary package via the command-line. It failed because it was missing `chezscheme`.

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
