### ISSUE TITLE
Can't use scheme target globally following instructions from `INSTALL.md`

### ISSUE THREAD

**Issue by MaisaMilena** [uwu-tech/Kind#292]
### Describe the bug
I followed the instructions from [install](https://github.com/uwu-tech/Kind/blob/master/INSTALL.md). I got the binary file and see the available Kind commands when typing `./bin/kind-scm` inside `Kind/bin/scm`. 

Unfortunately, `sudo make install` doesn't work. Got the following error when in `Kind/bin/scm`:
```
chmod +x bin/kind-scm
cp bin/kind-scm /usr/local/bin/
cp: directory /usr/local/bin does not exist
make: *** [install] Error 1
```
And this one in `Kind/bin/scm/bin`:
```
make: *** No rule to make target `install'.  Stop.
```

### To Reproduce
1. Follow the steps to build from [source](https://github.com/uwu-tech/Kind/blob/master/INSTALL.md)
2. Inside `Kind/bin/scm/bin` and `Kind/bin/scm` run `sudo make install`

### Expected behavior
Be able to use `kind-scm` globally

### Environment (please complete the following information):
 - OS: macOS 11.2.3
 - Kind version kind@1.0.92

### Work around
1. Copy `Kind/bin/scm/bin/kind-scm` to `Kind/base`
2. Run `chmod +x kind-scm` to make it an executable file
3. Inside `Kind/base` use it by typing `./kind-scm`

**Comment by rigille** [comment]
Thanks Maisa, I'm reworking the build system with Nix instead of GNU Make to make it simple and reproducible.

**Comment by MaisaMilena** [comment]
> Thanks Maisa, I'm reworking the build system with Nix instead of GNU Make to make it simple and reproducible.

thank you, Rígille! You are doing a great job with the scheme target :3
