### ISSUE TITLE
Error while building Kind using nix-build and node2nix

### ISSUE THREAD

**Issue by wkolowski** [uwu-tech/Kind#293]
### To Reproduce
When I try to install new(er) versions of Kind through Nix (using node2nix), when I issue the command `nix-build`, I get:

```
trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938
these derivations will be built:
  /nix/store/55lm189dnpg595rys7cjlkcsfm2w6jvf-node_kind-lang-1.0.0.drv
  /nix/store/hsv1alrrxqnp9x0n1m40955z9ksiz1ll-node-tarball-kind-lang-1.0.0.drv
  /nix/store/ygs06l2fph2dazyyzyfyv27llhipizy6-node-dependencies-kind-lang-1.0.0.drv
  /nix/store/pgdlzixj7ypvfahmzpdrq6jfahkhp24k-node-shell-kind-lang-1.0.0.drv
building '/nix/store/hsv1alrrxqnp9x0n1m40955z9ksiz1ll-node-tarball-kind-lang-1.0.0.drv'...
building '/nix/store/55lm189dnpg595rys7cjlkcsfm2w6jvf-node_kind-lang-1.0.0.drv'...
unpacking sources
unpacking source archive /nix/store/3vjkm8305c9lgclm2124zlniyj7a8kz6-Kind2
source root is Kind2
patching sources
configuring
no configure script, doing nothing
building
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
installing
unpacking source archive /nix/store/3vjkm8305c9lgclm2124zlniyj7a8kz6-Kind2
unpacking source archive /nix/store/ilahf43mmlasd5hyhh6djb86yddq9sl9-formcore-js-0.1.91.tgz
unpacking source archive /nix/store/zgswvnn8l6nl2vbi8wmyfdqbjyyjrmdq-kind-lang-1.0.90.tgz
pinpointing versions of dependencies...
patching script interpreter paths in .
./kind-lang/node_modules/kind-lang/src/main.js: unsupported interpreter directive "#!/usr/bin/env -S node --stack-size=100000" (set dontPatchShebangs=1 and handle shebang patching yourself)
builder for '/nix/store/55lm189dnpg595rys7cjlkcsfm2w6jvf-node_kind-lang-1.0.0.drv' failed with exit code 1
error: build of '/nix/store/55lm189dnpg595rys7cjlkcsfm2w6jvf-node_kind-lang-1.0.0.drv', '/nix/store/hsv1alrrxqnp9x0n1m40955z9ksiz1ll-node-tarball-kind-lang-1.0.0.drv', '/nix/store/pgdlzixj7ypvfahmzpdrq6jfahkhp24k-node-shell-kind-lang-1.0.0.drv' failed
```

### Expected behavior
No error.

### Environment (please complete the following information):
 - OS: NixOS 21.03
 - Kind version: this happens for Kind 1.0.90 and some older versions, but not for 1.0.37.

### Additional Context
I know the error message tells me to "patch shebangs" manually, but I spent somewhere between 30 mins and 1 hour trying to figure it out and so far I think that would be just a waste of time and I'm using an older version of Kind (1.0.37 to be precise). It would be very kind (pun intended) if somebody just reverted `#!/usr/bin/env -S node --stack-size=100000` to whatever it was in 1.0.37, it would probably save lots of trouble for Nix people.

**Comment by rigille** [comment]
It's hard to change the shebang line because it would break the workflow of some of our collaborators :/
I've been working on using nix to manage our builds and development dependencies and I've been able to make a working flake for `kind-scm`. Could you try it?
I couldn't turn the js target into a flake, if you had any ideas on how to do that I would appreciate it very much 🙂

**Comment by algebraic-dev** [comment]
Closed because the repository now only contains the code for the Kind2 language.
