### ISSUE TITLE
Is this the right definition for pow in Nat?

### ISSUE THREAD

**Issue by saludes** [uwu-tech/Kind#302]
If I follow the definition at
https://github.com/kind-lang/Kind/blob/a7df862d86ed5ff24036ab8c87639dd8f7567fb3/base/Nat/pow.kind#L3

It gives me that x^y = x, for all x and y.

**Comment by rigille** [comment]
Indeed that definition was incorrect. Thanks! For example
```
Test: Nat
  Nat.pow(2, 3)
```
was returning 8 because the compiler optimizes the operation to native BigInt exponentiation. However
```
Test: Nat.pow(2, 3) == 8
  refl
```
didn't typecheck and
```
Test: Nat.pow(2, 3) == 2
  refl
```
did because the typechecker unfolds the actual definitions. That's fixed by c1b0f7b.
